// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPa8H4FW_O-KLjAl6YtX4JEYhH9E5tog',
    appId: '1:217162958623:web:e83973003d70f6270a922a',
    messagingSenderId: '217162958623',
    projectId: 'chatapp-59005',
    authDomain: 'chatapp-59005.firebaseapp.com',
    storageBucket: 'chatapp-59005.appspot.com',
    measurementId: 'G-GHRTZCK0ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7tYYi-xFwleNkwvbJfOzDFQ--1OkvTNU',
    appId: '1:217162958623:android:7adee7022acbc8120a922a',
    messagingSenderId: '217162958623',
    projectId: 'chatapp-59005',
    storageBucket: 'chatapp-59005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_a3IK_pHxFGLyPhuyk0cx3iDqKQxwyeg',
    appId: '1:217162958623:ios:edf075dbae8350480a922a',
    messagingSenderId: '217162958623',
    projectId: 'chatapp-59005',
    storageBucket: 'chatapp-59005.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_a3IK_pHxFGLyPhuyk0cx3iDqKQxwyeg',
    appId: '1:217162958623:ios:04687f73f8ab5dae0a922a',
    messagingSenderId: '217162958623',
    projectId: 'chatapp-59005',
    storageBucket: 'chatapp-59005.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
